### ISSUE TITLE
Realtime Updates - Text Frequency

### ISSUE THREAD

**Issue by RwHendrickson** [RwHendrickson/AQ_SpikeAlerts#19]
After running the script over the weekend, I noticed that we got 6 alerts for a single sensor in the span of 5 1/2 hours (all between 10 and 30 minutes in duration).

As the code stands now, this would have resulted in 5 "new" and 5 "ended" alert messages for all users nearby. 

How do we want to correct this?

**Comment by blackhat-hemsworth** [comment]
I still have to do some thinking/checking the current process but just FYI I will probably end up shooting you a proposal for how _I think_ we should handle this before I code anything (just to make sure it's aligned with the overall project vision). 

For now just noting two assumptions that I am going to start with:
1. We should prefer any solutions that aren't twilio specific here (just to make the project more adaptable if twilio blows up, other folks want to adapt to other vendors, etc)
2. We should assume that even if the sensors are wiggy, the initial high reading is trustworthy (like we aren't waiting for multiple high reads to _start_ an alert, just tracking when to _end_ one). If we end up needing to see two spikes or whatever to start an alert, that could be a whole other thing, so best to treat the two as separate

**Comment by blackhat-hemsworth** [comment]
**My thoughts:**
We should add a column to the "Active Alerts" table that tracks last_reading / last_elevated_reading time. Using this column, we can create some static configurable variable to set the _amount of time_ the program waits before declaring an alert "over". We keep the alert active as long as the last elevated reading was within that span of time.

We should probably also persist that column into the "Archived Alert" table for added specificity as needed when reporting

**Pros:**
1. Solves for both random oscillations downwards in the sensor readings AND cases where maybe the average hovers just below the threshold and just above for an extended period of time
2. Using a time column would scale upwards and make the design more scalable (would still follow same behavior if MAIN ran every minute or every hour)
3. This can allow for more specificity in the reports 
4. Could come in handy debugging -- if for example a sensor records a high value and then stops giving readings, this could show why it is "stuck" on alert _(actually noticed right now if a sensor misses a reading it looks like we would declare the alert over, this could help solve for that if not intended)_

**Cons:** 
1. Having alerts always have a longer "duration" than the time between max readings could be confusing. It might be confusing to people why we would wait 30mins-1hr-etc. to "declare" an alert over (although I am not sure about this, I never wanted to jump outside as soon as the wildfire stuff was in the yellow-green range this past summer). 
2. Slightly more complicated coding in the alert sorting function, which is a key function (it'd spoil a bit of the nice list operations)
3. Could be more complicated if it needed to extrapolate to clustered alerts -- but this is kind of true of everything, and based on my imagination of how such a scenario would work, it could either a) wait until all clustered sensors had 30 minutes straight of good readings b) have some procedure for removing sensors with a single good reading, adding them back if they had another bad one, and waiting 30mins for the last sensor.

**How we'd do it:** 
1. We'd need to add/initialize dbs with an extra column 
2. Within sort_sensors_for_updates we'd need to 
- split out two new lists previous_active > 1hr & previous_active <= 1 hr.
- redefine ongoing as its current definition PLUS any previous_active <= 1 hr
- redefine ended as previous_active > 1hr - current_active_spike_sensors
3. Add to the UPDATE statement in update_max_reading to insert runtime (from the get_spikes_df output) into the row that it updates. Possibly we would change this function's name. 
- even though the "ongoing" alerts _returned by sort_sensors_for_updates_ will have the alert_ids for those previous_active <= 1 hr alerts, they would never make it to this function (if I read code right) because they'd still not match spikes_df indices (ongoing_spikes_df = spikes_df[spikes_df.sensor_index.isin(ongoing_spike_sensors)])

**Comment by RwHendrickson** [comment]
I'm going to have to take some time to parse through ^  Appreciate all the thought you put in and will circle back this weekend!

**Comment by RwHendrickson** [comment]
I think you're absolutely right about changing the database.

What if we added last_elevated as a datetime field of "PurpleAir Stations"
Then any alert/user could have a SQL view of the last time they were
elevated.

This could then inform us of:

- Should we send out an end alert message (10-30 minute lag)?

- Should we reactivate an alert (move it back to "active alerts"

- Should we send another alert message?

**Comment by blackhat-hemsworth** [comment]
Yes!! That’s a great idea. I think it means a bit of extra DB interaction (we’d have to hit the sensor db at probably a similar two points in the  workflow, grouping alerts and updating ongoing… possibly three points if we don’t already hit it for _new_ alerts) but it opens up a lot of options. 

Everything you mentioned and possibly could be leveraged to tell users when alerts that stretched past communication hours ended (or prevent the message from sending if they had a recent elevated read on the same sensor)?

**Comment by RwHendrickson** [comment]
I'm going to add a new issue for creating this field as well as trimming down others in the PurpleAir Stations

#33

**Comment by RwHendrickson** [comment]
Okay, I think this is good for now! We have an adjustable parameter, alert_lag=20 (adjustable parameter in minutes), in Our_Queries.Get_not_elevated_sensors() that allows for adjusting when to consider a sensor not under alert (last elevated> 20 minutes ago. It is called in GetSort_Spikes.Sort_sensor_indices()

This effectively lags the archiving of alerts, allowing for a sensor to fall below the threshold for some time but still remain on alert. 

But we may want to come back to this to touch on 

https://github.com/RwHendrickson/AQ_SpikeAlerts/issues/19#issuecomment-1817415648

and 

https://github.com/RwHendrickson/AQ_SpikeAlerts/issues/19#issuecomment-1815662831
