### ISSUE TITLE
Organization - Condense MAIN.py

### ISSUE THREAD

**Issue by RwHendrickson** [RwHendrickson/AQ_SpikeAlerts#24]
I am not as familiar with how to do this..

 Does it mean we make our scripts into modules? Have more parent functions?

**Comment by blackhat-hemsworth** [comment]
I don't think this is really _condensation_ but it would be cool to change these to import module statements:
exec(open('Get_spikes_df.py').read())
exec(open('Create_messages.py').read())
exec(open('twilio_functions.py').read())
exec(open('Update_Alerts.py').read())
exec(open('Send_Alerts.py').read())
exec(open('Daily_Updates.py').read())

And therefore change function references to have a prefix (which it looks like you already started with Daily_Updates). There are comments in a lot of places but when there aren't, it's tough to tell what script something is originating in.

**Comment by RwHendrickson** [comment]
Heard! I'm going to shift a lot of my focus into making it easier to read the scripts

**Comment by RwHendrickson** [comment]
Working on this a little 361da96 & 962a8d2 & e90d068

@blackhat-hemsworth Wondering about your thoughts on changing up the script/module names. Here's a new organization I've been thinking about:

Basic_PSQL - 2 functions that intake a psycopg2.sql.SQL string. One that returns a response, the other updates our database
Daily_Updates - include a new sort_sensor_ids function for daily updates
Get_Spikes - includes sort_sensor_ids
New_Spikes
Ongoing_Spikes
Ended_Spikes
Send_Alerts
Twilio_Functions
REDCap_Functions
PurpleAir_Functions

**Comment by blackhat-hemsworth** [comment]
Not an expert with this stuff but that sounds great  -- I know keeping the API stuff (twilio, redcap, purpleair) blocked out is good practice to organize dependencies. And the rest of it is intuitive to me, matches workflow diagram nicely. 

I think especially the PSQL stuff will be awesome since if I understand correctly, that would let us keep all the pg_connection_dict details in that specific file, which would make a lot of functions lighter/more legible (in addition to ensuring that we don't have multiple connections/cons/cursors open at once, which I was thinking yesterday is definitely possible -- not sure if it would cause any technical issues or just be one extra object that the process has open, but still probably better to avoid).

The only caution I have is I _think_ if you rename a file in development branch while someone else has edits _on that file_ in another branch, it can get goofy with commits / merges / etc. I think it would still be resolved by just renaming the file in the other branch, and then changes would compare normally. But I'm not 100% sure. (I also don't have anything I am working on right now, and I'm not sure if Dan would have changes in the modules themselves, but just noting in case)

**Comment by RwHendrickson** [comment]
@blackhat-hemsworth @danraskin when you both get a chance, could you review the contents of the [Modulation](https://github.com/RwHendrickson/AQ_SpikeAlerts/tree/Modulation) branch? 

Just want to be sure it doesn't mess up anything, but it's running well on my computer! Going to wrap up that work today by cleaning up Daily_Updates/Send_Alerts and creating a new module called REDCap_Functions.py

**Comment by RwHendrickson** [comment]
I think this is a good start to what we wanted here #42

**Comment by RwHendrickson** [comment]
New thoughts on decreasing parameters in workflow functions!

https://github.com/RwHendrickson/AQ_SpikeAlerts/pull/42#pullrequestreview-1742956435
